# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ClusterTable_new <- function(phylo) {
    .Call(`_Rogue_ClusterTable_new`, phylo)
}

ClusterTable_matrix <- function(xp) {
    .Call(`_Rogue_ClusterTable_matrix`, xp)
}

ClusterTable_decode <- function(xp) {
    .Call(`_Rogue_ClusterTable_decode`, xp)
}

COMCLUST <- function(trees) {
    .Call(`_Rogue_COMCLUST`, trees)
}

consensus_info <- function(trees, phylo) {
    .Call(`_Rogue_consensus_info`, trees, phylo)
}

robinson_foulds_all_pairs <- function(tables) {
    .Call(`_Rogue_robinson_foulds_all_pairs`, tables)
}

