# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'inst/include/**'
      - 'tests/testthat/**'
      - 'vignettes/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'inst/include/**'
      - 'tests/testthat/**'
      - 'vignettes/**'

name: mem-check

jobs:
  mem-check:
    runs-on: ubuntu-24.04 # Remember to update RSPM below to match

    name: valgrind ${{ matrix.config.test }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {test: 'tests'}
          - {test: 'examples'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/noble/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      LD_PRELOAD: /usr/lib/x86_64-linux-gnu/libasan.so.6  # Path to ASan runtime library

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - uses: ms609/actions/memcheck@main
        with:
          test: ${{ matrix.config.test}}
