on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'inst/include/**'
      - 'tests/testthat/**'
      - 'vignettes/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'inst/include/**'
      - 'tests/testthat/**'
      - 'vignettes/**'

name: mem-check

jobs:
  mem-check:
    runs-on: ubuntu-24.04

    name: valgrind ${{ matrix.config.test }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {test: 'tests'}
          - {test: 'examples'}

    env:
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: ms609/actions/memcheck@main
        with:
          test: ${{ matrix.config.test }}
          submodules: true
